spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}  # Kafka 브로커 주소를 환경 변수에서 읽어오고, 설정되지 않은 경우 기본값을 사용
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:chat-group}  # Kafka 컨슈머 그룹 ID를 환경 변수에서 읽어오고, 기본값 설정
      auto-offset-reset: ${KAFKA_AUTO_OFFSET_RESET:earliest}  # 컨슈머의 오프셋을 설정, 기본값은 earliest
    listener:
      missing-topics-fatal: ${KAFKA_MISSING_TOPICS_FATAL:false}  # 설정된 토픽이 없을 때 애플리케이션의 동작 방식을 설정, 기본값은 false